language: python
install:
- pip install -r requirements.txt
- pip install codecov
- pip install pytest-cov
jobs:
  include:
  - stage: test
    python: '3.4'
    script:
    - python -m pytest -v --cov=SAGA_optimize.py
  - stage: test
    python: '3.5'
    script:
    - python -m pytest -v --cov=SAGA_optimize.py
  - stage: test
    python: '3.6'
    script:
    - python -m pytest -v --cov=SAGA_optimize.py
  - stage: test
    python: '3.7'
    dist: xenial
    script:
    - python -m pytest -v --cov=SAGA_optimize.py

after_success:
  - codecov
